### ISSUE TITLE
Decrease replication_interval for Player MultiplayerSynchronizer

### ISSUE THREAD

**Issue by iiiCpu** [ic3bug/Godot-Simple-Multiplayer#3]
`replication_interval` of `0.2` sec is too big for FPS. Players' movements without interpolation are too fragmented. 

When I started demo, I thought there were something wrong with Godot. 

I would suggest you to set `replication_interval  = 0.01` . Or, at least, write in README that `replication_interval`  is big, so players would not be shocked by laggy picture.

**Comment by JohnnyUrosevic** [comment]
thank you so much for pointing this out. I was going crazy wondering why this was so choppy and thought i might have to abandon the godot networking api entirely
